---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(tccong)
options(width = 100)
```

# tccong

<!-- badges: start -->
<!-- badges: end -->

A simple interface to [TweetCongress](http://www.tweetecongress.com/) APIs 

## Installation

You can install the released version of **tccong** from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("tccong")
```

Or from Github

``` r
remotes::install_github("r-congress/tccong")
```

## Tweeters

Data returned from TweetCongress' Tweeters API

```{r}
## fetch tweeters data
twtrs <- tcc_tweeters()

## view data
twtrs
```

## Tweets

Data returned from TweetCongress' Tweets API

```{r}
## fetch tweeters data
twts <- tcc_tweets()

## view data
twts
```


## Stats

Data returned from TweetCongress' Stats API

```{r}
## fetch tweeters data
sts <- tcc_stats()

## view data
sts
```

